#!/usr/bin/env bash
set -euo pipefail
# Generated by scripts/build_install_script.py. Do not edit the embedded code.
# Remote: bash install.sh --repo art-shier/deployctl --version latest --user
# Local:  bash install.sh ./deployctl.pyz [destination]
python_command=${DEPLOYCTL_PYTHON:-python3}
if ! command -v "$python_command" >/dev/null 2>&1; then
  echo "Python >=3.10 is required; install Python or set DEPLOYCTL_PYTHON." >&2
  exit 1
fi
"$python_command" - "$@" <<'DEPLOYCTL_INSTALL_PY'
"""Standalone stdlib-only GitHub Release installer; embedded into install.sh."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys
import tempfile
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlsplit
from urllib.request import HTTPRedirectHandler, Request, build_opener

DEFAULT_REPOSITORY = 'art-shier/deployctl'
MAX_DOWNLOAD = 10 * 1024 * 1024
TAG = re.compile(r'v?[0-9]+\.[0-9]+\.[0-9]+(?:-[A-Za-z0-9][A-Za-z0-9.-]*)?\Z')


class SafeRedirect(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        old, new = urlsplit(req.full_url), urlsplit(newurl)
        if new.scheme != 'https' or new.username or new.password:
            raise ValueError('download redirect must remain HTTPS without URL credentials')
        redirected = super().redirect_request(req, fp, code, msg, headers, newurl)
        if redirected and (old.hostname, old.port) != (new.hostname, new.port):
            redirected.remove_header('Authorization')
            redirected.remove_header('Cookie')
        return redirected


def fetch(request, limit):
    try:
        with build_opener(SafeRedirect()).open(request, timeout=60) as response:
            content = response.read(limit + 1)
            if len(content) > limit:
                raise ValueError('download exceeds size limit')
            return content
    except HTTPError as exc:
        raise RuntimeError(f'GitHub HTTP {exc.code}; check release/version and repository access; private repositories require GH_TOKEN or gh auth login') from exc
    except (URLError, TimeoutError) as exc:
        raise RuntimeError('GitHub download failed; check network and HTTPS certificate') from exc


def digest_text(text):
    fields = text.strip().split()
    if not fields or not re.fullmatch(r'[a-fA-F0-9]{64}', fields[0]):
        raise ValueError('invalid SHA256 checksum')
    return fields[0].lower()


def artifact_version(path):
    result = subprocess.run([sys.executable, str(path), '--version'], capture_output=True, text=True, timeout=30)
    value = result.stdout.strip()
    if result.returncode or not TAG.fullmatch(value):
        raise ValueError('verified artifact does not report a valid deployctl version')
    return value.lstrip('v')


def github_release(repository, version, token, release_id=None):
    if not re.fullmatch(r'[A-Za-z0-9-]+/[A-Za-z0-9_.-]+', repository):
        raise ValueError('repository must be owner/repository')
    if version != 'latest' and not TAG.fullmatch(version):
        raise ValueError('version must be latest or a semantic version tag')
    if release_id is not None:
        if not re.fullmatch(r'[1-9][0-9]*', str(release_id)) or version == 'latest':
            raise ValueError('draft release verification requires a numeric release ID and exact version')
        route = str(release_id)
    else:
        route = 'latest' if version == 'latest' else 'tags/' + quote(version, safe='')
    headers = {'User-Agent': 'deployctl-installer', 'Accept': 'application/vnd.github+json',
               'X-GitHub-Api-Version': '2022-11-28'}
    if token:
        headers['Authorization'] = 'Bearer ' + token
    release = json.loads(fetch(Request(f'https://api.github.com/repos/{repository}/releases/{route}', headers=headers), 1024 * 1024))
    tag = release.get('tag_name', '')
    if not isinstance(tag, str) or not TAG.fullmatch(tag) or (version != 'latest' and tag != version):
        raise ValueError('GitHub release version does not match requested version')
    assets = release.get('assets', [])
    def asset(name, limit):
        matches = [item for item in assets if item.get('name') == name]
        if len(matches) != 1:
            raise ValueError(f'release must contain exactly one {name}')
        url = matches[0]['url']
        parsed = urlsplit(url)
        prefix = f'/repos/{repository}/releases/assets/'
        if (parsed.scheme != 'https' or parsed.hostname != 'api.github.com' or parsed.username
                or parsed.password or not parsed.path.startswith(prefix)):
            raise ValueError('unexpected GitHub asset API URL')
        return fetch(Request(url, headers=dict(headers, Accept='application/octet-stream')), limit)
    expected = digest_text(asset('deployctl.pyz.sha256', 4096).decode('utf-8'))
    return asset('deployctl.pyz', MAX_DOWNLOAD), expected, tag


def atomic_write(path, content, mode):
    fd, tmp = tempfile.mkstemp(prefix='.deployctl-', dir=path.parent)
    try:
        with os.fdopen(fd, 'wb') as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(tmp, mode)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def install(artifact=None, install_dir=None, repository=DEFAULT_REPOSITORY, version='latest',
            token='', no_alias=False, force=False, expected_sha256=None, primary_name='deployctl', release_id=None):
    if not re.fullmatch(r'[A-Za-z0-9_.-]+', primary_name) or primary_name in ('.', '..'):
        raise ValueError('invalid destination command name')
    if artifact:
        path = Path(artifact).expanduser().resolve()
        if path.stat().st_size > MAX_DOWNLOAD:
            raise ValueError('artifact exceeds size limit')
        content = path.read_bytes()
        expected = digest_text(path.with_name(path.name + '.sha256').read_text(encoding='utf-8'))
        tag = None
    else:
        content, expected, tag = github_release(repository, version, token, release_id)
    actual = hashlib.sha256(content).hexdigest()
    if actual != expected or (expected_sha256 and actual != digest_text(expected_sha256)):
        raise ValueError('artifact checksum mismatch; existing installation is unchanged')
    with tempfile.TemporaryDirectory(prefix='deployctl-verify-') as tmp:
        executable = Path(tmp) / 'deployctl.pyz'
        executable.write_bytes(content)
        detected = artifact_version(executable)
    if tag and detected != tag.lstrip('v'):
        raise ValueError('artifact version does not match release tag')
    tag = tag or 'v' + detected
    # A shell prefix preserves the selected Python, including paths with spaces.
    # Python reads the unchanged ZIP payload after this prefix.
    installed_content = content
    if content.startswith(b'#!'):
        payload = content.split(b'\n', 1)[1]
        launcher = '#!/bin/sh\nexec ' + shlex.quote(sys.executable) + ' "$0" "$@"\n'
        installed_content = launcher.encode('utf-8') + payload
    installed_digest = hashlib.sha256(installed_content).hexdigest()
    folder = Path(install_dir).expanduser().resolve()
    marker = folder / '.deployctl-install.json'
    previous = {}
    if marker.exists():
        if marker.stat().st_size > 65536:
            raise ValueError('installation metadata exceeds size limit')
        previous = json.loads(marker.read_text(encoding='utf-8'))
    names = list(dict.fromkeys([primary_name] + ([] if no_alias else ['ctl'])))
    previous_files = previous.get('files', {})
    backups = {}
    for name in names:
        target = folder / name
        if target.is_symlink():
            raise ValueError(f'{name} is a symlink; choose a different directory or --no-alias')
        if target.exists():
            if not target.is_file() or target.stat().st_size > MAX_DOWNLOAD:
                raise ValueError(f'{name} is not a supported existing executable')
            old = target.read_bytes()
            managed = (previous.get('repository') == repository
                       and previous_files.get(name) == hashlib.sha256(old).hexdigest())
            if not managed and not force:
                raise ValueError(f'{name} is not managed by this installer; use another directory, --no-alias or explicitly --force')
            backups[name] = (old, target.stat().st_mode & 0o777)
        else:
            backups[name] = None
    folder.mkdir(parents=True, exist_ok=True)
    files = dict(previous_files) if previous.get('repository') == repository else {}
    files.update({name: installed_digest for name in names})
    state = {'schema_version': 1, 'repository': repository, 'version': tag,
             'sha256': actual, 'files': files, 'directory': str(folder)}
    changed = []
    try:
        for name in names:
            atomic_write(folder / name, installed_content, 0o755)
            changed.append(name)
        atomic_write(marker, (json.dumps(state, indent=2) + '\n').encode(), 0o600)
    except OSError:
        for name in reversed(changed):
            if backups[name] is None:
                (folder / name).unlink(missing_ok=True)
            else:
                old, mode = backups[name]
                atomic_write(folder / name, old, mode)
        raise
    return state


def resolve_token():
    token = os.environ.get('GH_TOKEN') or os.environ.get('GITHUB_TOKEN')
    if token:
        return token
    try:
        result = subprocess.run(['gh', 'auth', 'token', '--hostname', 'github.com'], capture_output=True, text=True, timeout=15)
        return result.stdout.strip() if result.returncode == 0 else ''
    except (OSError, subprocess.TimeoutExpired):
        return ''


def main(argv=None):
    parser = argparse.ArgumentParser(description='Install deployctl and ctl from GitHub Release or a local artifact')
    parser.add_argument('artifact', nargs='?', help='optional local deployctl.pyz; adjacent checksum required')
    parser.add_argument('destination', nargs='?', help='legacy local install destination file')
    parser.add_argument('--repo', default=DEFAULT_REPOSITORY)
    parser.add_argument('--version', default='latest')
    parser.add_argument('--release-id', help='CI draft verification: numeric Release ID; requires exact --version')
    parser.add_argument('--user', action='store_true', help='install into ~/.local/bin')
    parser.add_argument('--install-dir', help='custom command directory')
    parser.add_argument('--no-alias', action='store_true', help='do not install the ctl alias')
    parser.add_argument('--force', action='store_true', help='explicitly replace unrelated existing command files')
    parser.add_argument('--sha256', help='optional independently obtained artifact SHA256')
    args = parser.parse_args(argv)
    try:
        if sys.version_info < (3, 10):
            raise ValueError('Python >=3.10 is required')
        if args.destination and (not args.artifact or args.install_dir or args.user):
            raise ValueError('legacy destination requires a local artifact and no directory flags')
        if args.user and args.install_dir:
            raise ValueError('choose --user or --install-dir')
        if args.artifact and args.release_id:
            raise ValueError('--release-id cannot be used with a local artifact')
        user_install = args.user or not hasattr(os, 'geteuid') or os.geteuid() != 0
        folder = args.install_dir or (Path.home() / '.local/bin' if user_install else Path('/usr/local/bin'))
        name = 'deployctl'
        if args.destination:
            target = Path(args.destination).expanduser().resolve()
            folder, name = target.parent, target.name
        state = install(args.artifact, folder, args.repo, args.version,
                        resolve_token() if not args.artifact else '', args.no_alias, args.force, args.sha256, name, args.release_id)
        print(f"Installed {state['version']} into {state['directory']}")
        print('Commands: ' + ', '.join([name] + ([] if args.no_alias or name == 'ctl' else ['ctl'])))
        if state['directory'] not in os.environ.get('PATH', '').split(os.pathsep):
            print(f'Add this directory to PATH: {state["directory"]}')
        return 0
    except (ValueError, OSError, RuntimeError, subprocess.TimeoutExpired) as exc:
        print(f'ERROR: {exc}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
DEPLOYCTL_INSTALL_PY
