"""Generate one self-contained Bash installer from the tested Python source."""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = '''#!/usr/bin/env bash
set -euo pipefail
# Generated by scripts/build_install_script.py. Do not edit the embedded code.
# Remote: bash install.sh --repo art-shier/deployctl --version latest --user
# Local:  bash install.sh ./deployctl.pyz [destination]
python_command=${DEPLOYCTL_PYTHON:-python3}
if ! command -v "$python_command" >/dev/null 2>&1; then
  echo "Python >=3.10 is required; install Python or set DEPLOYCTL_PYTHON." >&2
  exit 1
fi
"$python_command" - "$@" <<'DEPLOYCTL_INSTALL_PY'
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = HEADER + (ROOT / 'scripts/install_deployctl.py').read_text(encoding='utf-8').rstrip() + '\nDEPLOYCTL_INSTALL_PY\n'
    target = ROOT / 'install.sh'
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8') != content:
            raise SystemExit('install.sh is stale; run python scripts/build_install_script.py')
    else:
        target.write_text(content, encoding='utf-8', newline='\n')
    print('Installer generated source is current')


if __name__ == '__main__':
    main()
